### ISSUE TITLE
2018 Community Funds Budget

### ISSUE THREAD

**Issue by ciphs** [ciphs/community#1]
As initial arrangement for CIPHS community funds, 1 million CIPHS need to be arrange accordingly. The proposal as below:
1. Sub allocations, this part will cover 2018 expenses and will be delegate into micro milestone.
 a. CIPHS.ORG domain for few years - 100000 CIPHS
 b. CIPHS.ORG github page management - 100000 CIPHS
 c. CIPHS.ORG public relation on Telegram and Gitter - 100000 CIPHS
 d. CIPHS.ORG website maintenance - 100000 CIPHS
 e. CIPHS.ORG marketing & contest - 100000 CIPHS
 f.  Community Reserve - 500000 CIPHS

This proposal will need a review to achieve agreement. Any addtional suggestion or obejections are allow within comment with no needing to open new issue. Feel free to review. Thanks.

**Comment by nidscom** [comment]
Hi. How remain reserve are manage? That's lot of unused Ciphs. Funds balance will carry forward for next year development?

**Comment by ciphs** [comment]
Reseeve is up to proposal. In future we might use forum for making proposal and such.

**Comment by ciphs** [comment]
I will close this after 7 days and create a pr to this repo to verify all the allocation propose here has been agree. CIPHS will be transfer to allocated wallets as direct contribution from CIPHS [DevT Wallets](https://etherscan.io/address/0x896d4a6c5e627eb3b2546128fdb356894a009841) and Community [Bounty Wallets](https://etherscan.io/address/0xc0663a0e695c5602832d1aa4c669a95d5f077b85) here.

**Comment by ciphs** [comment]
Time have spoken. Proposal consider agree and without further a due i will close this issue and submit pr to this repo.
