### ISSUE TITLE
2018 Developer Funds Budget

### ISSUE THREAD

**Issue by ciphs** [ciphs/community#2]
Initial allocation is 1,000,000 CIPHS and will be use for early and future development. The specific as below:
1. Completed task:
 a. CIPHS.ORG logo making by @ciphs - 1000 CIPHS
 b. Github page opening by @ciphs -10000 CIPHS
 c. Early development code submission by @ciphs, @billiegate - 50000 CIPHS
 d. CIP1 contributor by @ciphs, @billiegate - 30000 CIPHS
 e. ERC223 proposal by @dexaran - 500 CIPHS
 f.  CIPHS.ORG domain and website by @ciphs, @nidscom - 10000 CIPHS

2.  Future Development
 a. web3 and api - 100000 CIPHS
 b. CIPHS official wallet - 100000 CiPHS
 c. CIPHS DAO Token - 100000 CIPHS
 d. Development reserve - 598,400 CIPHS

**Comment by ciphs** [comment]
Hi. I will need @Dexaran wallet address to transfer allocated Ciphs. You may email at 0x0@ciphs.org or telegram @ciphs.

**Comment by Dexaran** [comment]
0x01000b5fe61411c466b70631d7ff070187179bbf

**Comment by ciphs** [comment]
Case close. Pls refer
https://github.com/ciphs/community/issues/1
